### ISSUE TITLE
Button click to show the dialog causes flicker to parent window

### ISSUE THREAD

**Issue by denmase** [ajaykakkar93/Qlik-Sense-Dialog-Box#2]
Hi,

First of all thank you for the extension, it really helps me out. However, am having issue with flicker of parent window when the button to show the dialog is clicked. I tried to narrow down the culprit, it is because of this line of code in DialogBox.js

210 `qlik.resize(this);`

When I commented this line out, flicker is gone, but does it have other impact? I'm sorry I'm a newbie to Qlik Sense Extensions so I don't really understand how the extension really works.

Thank you

**Comment by denmase** [comment]
@ajaykakkar93 any comment on this?

**Comment by ajaykakkar93** [comment]
@denmase yes you can do that it will not impact.

**Comment by denmase** [comment]
Great, thanks for your reply. I'll close the issue.
